package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	// Find repo root (walk up from executable location)
	outDir := filepath.Join("..", "..", "docs", "research")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	// Generate datasets
	custData := customerData()
	balData := balanceData()
	nimPts := nimData()
	boePts := boeRateData()

	// Chart sections: title, 3 SVGs (hand-rolled, go-charts, margaid)
	type section struct {
		title                    string
		handrolled, gochart, mar string
	}

	sections := []section{
		{
			title:      "Customer Count",
			handrolled: hrCustomerCount(custData),
			gochart:    gcCustomerCount(custData),
			mar:        mgCustomerCount(custData),
		},
		{
			title:      "Balance History (dual line)",
			handrolled: hrBalances(balData),
			gochart:    gcBalances(balData),
			mar:        mgBalances(balData),
		},
		{
			title:      "NIM (bps)",
			handrolled: hrNIM(nimPts),
			gochart:    gcNIM(nimPts),
			mar:        mgNIM(nimPts),
		},
		{
			title:      "BoE Base Rate",
			handrolled: hrBoERate(boePts),
			gochart:    gcBoERate(boePts),
			mar:        mgBoERate(boePts),
		},
	}

	var body strings.Builder
	for _, sec := range sections {
		body.WriteString(fmt.Sprintf(`
    <h2 class="title is-4 mt-6">%s</h2>
    <div class="columns">
      <div class="column">
        <div class="box">
          <h3 class="subtitle is-6 has-text-centered">Hand-rolled SVG</h3>
          %s
        </div>
      </div>
      <div class="column">
        <div class="box">
          <h3 class="subtitle is-6 has-text-centered">go-analyze/charts</h3>
          %s
        </div>
      </div>
      <div class="column">
        <div class="box">
          <h3 class="subtitle is-6 has-text-centered">margaid</h3>
          %s
        </div>
      </div>
    </div>`, sec.title, sec.handrolled, sec.gochart, sec.mar))
	}

	html := fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Chart Renderer Comparison</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css">
  <style>svg { max-width: 100%%; height: auto; }</style>
</head>
<body>
  <nav class="navbar is-primary">
    <div class="navbar-brand">
      <a class="navbar-item has-text-weight-bold" href="../">GoBank</a>
    </div>
  </nav>
  <section class="section">
    <div class="container is-fluid">
      <h1 class="title">Chart Renderer Comparison</h1>
      <p class="subtitle">4 datasets rendered by 3 engines — hand-rolled SVG, go-analyze/charts, and margaid</p>
%s
    </div>
  </section>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>Generated by <code>cmd/chartcompare</code> — <a href="https://git.bytestone.uk/hum3/gobank">git.bytestone.uk/hum3/gobank</a></p>
    </div>
  </footer>
</body>
</html>
`, body.String())

	outPath := filepath.Join(outDir, "chart-comparison.html")
	if err := os.WriteFile(outPath, []byte(html), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Wrote %s\n", outPath)
}
